---
services:
  explorer:
    build:
      context: .
      target: dev
    image: ghcr.io/opendatacube/explorer:dev
    volumes:
      - .:/code
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    tty: true
    stdin_open: true
